"""A synthetic population-yield-climate model, for exercising the pipeline.

Not a scientific model and not a stand-in for one. It exists so the harness can
be run end to end before any real data is in hand, and it is deliberately built
with a known defect: `yield_gain` and `climate_scale` only ever appear as a
product, so no data generated by this model can separate them. The dry run must
detect that, or the harness does not work.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np

PARAM_NAMES = ["yield_gain", "climate_scale", "carrying_capacity", "growth_rate"]


@dataclass(frozen=True)
class SyntheticSeries:
    years: np.ndarray
    population: np.ndarray
    climate: np.ndarray
    #: One sigma, in people. Reconstructions are not measurements.
    sigma: float


def simulate(theta: np.ndarray, climate: np.ndarray, p0: float = 1000.0) -> np.ndarray:
    """Logistic growth whose carrying capacity is modulated by climate."""
    yield_gain, climate_scale, carrying_capacity, growth_rate = (float(t) for t in theta)

    population = np.empty(climate.size, dtype=float)
    current = p0
    for i, anomaly in enumerate(climate):
        # yield_gain and climate_scale enter only as this product.
        capacity = carrying_capacity * (1.0 + yield_gain * climate_scale * anomaly)
        capacity = max(capacity, 1.0)
        current = current + growth_rate * current * (1.0 - current / capacity)
        current = max(current, 1.0)
        population[i] = current
    return population


def make_series(
    theta_true: np.ndarray,
    n_years: int = 120,
    sigma: float = 15.0,
    seed: int = 20260806,
) -> SyntheticSeries:
    rng = np.random.default_rng(seed)
    years = np.arange(n_years, dtype=float)
    climate = np.sin(years / 11.0) + 0.3 * rng.standard_normal(n_years)
    truth = simulate(theta_true, climate)
    observed = truth + sigma * rng.standard_normal(n_years)
    return SyntheticSeries(years=years, population=observed, climate=climate, sigma=sigma)


def negloglik(theta: np.ndarray, series: SyntheticSeries) -> float:
    predicted = simulate(np.asarray(theta, dtype=float), series.climate)
    residual = (series.population - predicted) / series.sigma
    return float(0.5 * np.sum(residual**2))


def summary_output(theta: np.ndarray, series: SyntheticSeries) -> float:
    """Terminal population. The scalar the sensitivity analysis is run against."""
    return float(simulate(np.asarray(theta, dtype=float), series.climate)[-1])
